# from name: plasmabio-template-r

name: M1MEG-UE1-TP6-R-lab3
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
 # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - nbresuse
  - libgomp
  - pip
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  
  # R environment
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  # JupyterLab Variable inspector
  # https://github.com/lckr/jupyterlab-variableInspector
  - r-repr
  - pip:
    - lckr-jupyterlab-variableinspector
  - nbresuse
  - libgomp
  # R packages
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-ggplot2
  - r-kernsmooth
  - r-gplots
