# from name: plasmabio-template-r

name: M1MEG-UE1-TP6-R
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab=3
  - nbresuse
  - nodejs
  - libgomp
  - r-irkernel
  - r-base>=4.1.0
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-ggplot2
